### PR TITLE
MOBA abilities don't belong in a GSG game.1

### PR DESCRIPTION
**Pull request by lolmemes369**
Staff office plan 
cost  0.14-> 0.125
removed 20% planning and decreased planning speed to 200% from 400%  
Conserve Supplies
reduced supply consumption from -20% to -10%  (yeah clicking a button to get reduced supply is stupid but for now I will keep a little bit)
Makeshift bridges
river attack 20% to 15%  
Requisition Winter supplies
Removed the supply consumption so this isn't picked over conserve supplies

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
I mean I like this too I never approved of a moba ability in the game either.  Anyone else not in favor if these changes??

**Comment by Ruling-0** [comment]
I generally like it, but I think staff office plan can have its cost reduced to 0.1 if its being gutted that hard, esp. given the newer relative lack of command power.

**Comment by Narizna** [comment]
never enjoyed the abilities personally - even if they were used effectively in some circumstances. I believe it to be a layer in the game that is unnecessary and frustrating for players.

**Comment by lolmemes369** [comment]
> I generally like it, but I think staff office plan can have its cost reduced to 0.1 if its being gutted that hard, esp. given the newer relative lack of command power.
yeah that's fine. I don't like the idea that you have to select x < 8 units put them under a separate general and click the button. it is pretty dumb. maybe there is a way to make it work for 24 units but not as op. If anything these should be minor things and balance should not be made around these command abilities.

**Review by Ruling-0 — APPROVED** [review]

**Comment by GrenadierSchubes** [comment]
Pushing this since it got ruling approval.

**Pull request merged**
