### PR TITLE
China rework Japan Larp

### PR DESCRIPTION
**Pull request by GrenadierSchubes**
owner = PAR per state of larp them removal of resources

### CODE REVIEW

**Review by Mookubooku — APPROVED** [review]
Paraguay was the real winner of WWII.

**Review by lolmemes369 — CHANGES_REQUESTED** [review]
doesn't this nerf japan? You don't get the equipment from annexing the PRC.

**Comment by GrenadierSchubes** [comment]
This is a work in progresss

**Comment by Narizna** [comment]
I converted to Draft while it is WIP.

For the game's sake Annexing china was a way to boost Japan, however Historically Japan never took all of China and I believe we can give Japan/Manchu other things that would still Improve and allow for power spikes without relying on Annex/cap mechanic.

This change would not be so simple as to just make parts of China unaligned and that's it - will require (in my opinion) additional changes for an interesting experience.

**Pull request closed without merging**
