### PR TITLE
Lowered gun IC

### PR DESCRIPTION
**Pull request by sebsauve34**
I am once again asking for lower gun IC.

### CODE REVIEW

**Comment by AnonymousRevan** [comment]
I like it

**Review by AnonymousRevan — APPROVED** [review]
I supprt this

**Comment by Narizna** [comment]
Is this lowering the IC so more guns can be transported by each convoy? just so I'm not brain dead...

**Review by lolmemes369 — APPROVED** [review]

**Review by Mookubooku — APPROVED** [review]
Small changes but moving in the right direction.

**Pull request merged**
