### PR TITLE
Tobruk changes

### PR DESCRIPTION
**Pull request by BrianCatster**
Fixed Australia advisors I forgot to fix the other week
Changed Tobruk to a urban tile with lv 3 fort (-30%+ -45% attack)

### CODE REVIEW

**Comment by Ruling-0** [comment]
Is the other mountain province changed to hills that port 2 tiles West of Tobruk?

**Review by GrenadierSchubes — APPROVED** [review]
Looks good I see the urban and hills tiles added.  Are we just changing these ones or also a third?

**Review by Mookubooku — APPROVED** [review]
Looks good to me. Hill & urban tiles make more sense than mountains there.

**Comment by GrenadierSchubes** [comment]
Is there need to keep this open?   Is it just two tiles being changed or is that all?

**Review by lolmemes369 — APPROVED** [review]
Approved. Will have to see it in action to really see.
 
Side note: I wonder if adding some extra provinces would make that spot more interesting.

**Pull request merged**
