### PR TITLE
Spain industry rebalance

### PR DESCRIPTION
**Pull request by sebsauve34**
Adding more industry to spain to compensate for the new civil war mechanic, atm the nation feels terrible to play and has no impact due to having the AI control most of the industry rich parts of spain for 3 years, making the nation have 0 potential to produce equipment and have a decent economy. For reference, it starts with 29 owned civs and 18 mils, but when the civil war starts, you sit at 6 civs and 4 mils at the start and gradually work your way back up. On top of that, you have the stability penalty from being at war the entire time, gaining even less output / PP / consumer goods. I added around 9 civs on the states it starts with and around 5 mils, making them have 15 civs and 9 mils at the start of the war and going up to 14 mils and 20 civs after the first few states transfers early on. I also added simular industry in republican land that you get later so you have a better industry when the war ends. It would mean spain starts with around 40 civs and 20 mils at the start but you lose more than half during the war. I'll try to test it in SP to adjust factory counts, since I am definitely starting with a potentially too high factory count to see if its playable then work it down to a reasonable level if needed.

### CODE REVIEW

**Comment by sebsauve34** [comment]
I also removed the focus being blocked by civil war so spain can progress it's focus tree and actually be playable.

**Comment by Narizna** [comment]
the change to the civil war also probably "effectively" removes Spain's ability to be a lend lease factory man to the rest of the axis. Now I don't think recent Spain players have "played" he strategy - but typically it requires you had a good industry for a longer time to build up equipment.

**Comment by Ruling-0** [comment]
Are the three state deletions a mistake?

**Comment by GrenadierSchubes** [comment]
Let me know when this is final so we can review and push tonight as RH and Teutonic finished their sides

**Comment by sebsauve34** [comment]
The 3 delete werent a mistake, I think the industry should be fair now, can always adjust next game if need be, I don't have anymore changes to add if you want to push it.

**Review by Ruling-0 — APPROVED** [review]
Please comment the final industry numbers

**Review by RH-131 — APPROVED** [review]

**Pull request merged**
