### PR TITLE
tech and buildings

### PR DESCRIPTION
**Pull request by lolmemes369**
naval base cost 4k to 6k

moved floating harbor to 1944 tech.

starting from 5 each construction tech allows you to build one more level of infrastructure, coastal fort, fort, naval base, and air base.

Quick change but maybe a specific tech that starts in 1939 and ends in 1944 would be better.

### CODE REVIEW

**Comment by Mookubooku** [comment]
> Harbors should be more expensive than a supply depot, thoughts?

I would think so.

**Comment by Mookubooku** [comment]
Sure? Basically, we want it to be more appealing to actually build railroads and supply hub(s) rather than just slapping down a port and calling it a day.

**Review by Mookubooku — APPROVED** [review]
Infrastructure restrictions may be questionable but should reduce bloat. Harbors and supply hub changes look good. Ultimately, we want players to prefer building railroads and supply hubs over ports.

**Review by GrenadierSchubes — APPROVED** [review]
looks good to me

**Pull request merged**
