### PR TITLE
Brian's take on doctrines

### PR DESCRIPTION
**Pull request by BrianCatster**
Superior Firepower removed 2.5% supply consumption

Grand Assault lowered army soft attack 10%>5%

Elastic Defense increased Tank HP 150%>200%

### CODE REVIEW

**Comment by BrianCatster** [comment]
Could also lower Land night attack by 5% since that is apparently what is broken about the doctrine

**Comment by Ruling-0** [comment]
I prefer this smaller set of changes
How about grand assault 7.5% SA, remove 5% night attack?

**Comment by Mookubooku** [comment]
I agree with removing the supply consumption debuff from SF but I'm not sure why people keep wanting to nerf GBP.

**Comment by lolmemes369** [comment]
i don't think the supply should change tbh for SF

MA:
        DB: -10% supply consumption
        MM:  -20% supply consumption
GBP: 
        Assault: -5% supply consumption
        Infiltration: -10% supply consumption
SF:
        Integrated: +2.5% supply consumption
        Dispersed: +5%    supply consumption
MW:
       +/- 0% supply consumption (aka no change) (currently -5%)
  if anything GBP gets its supply consumption halved. MM can also go from -20% to -15%  or both GBP and mass assault get less -%.

**Pull request closed without merging**
