### PR TITLE
USA workers nerf, big business buff

### PR DESCRIPTION
**Pull request by sebsauve34**
Swap the consumer goods penalty from big businesses to the workers. Idea is you get the build more factories with the speed from big business and get no consumer goods penalty and workers gets less factories but produces more with the factories it has with extra output / production efficiency, Atm workers don't get consumer goods penalty and business does.

### CODE REVIEW

**Review by Mookubooku — APPROVED** [review]
Looks good to me.

**Comment by Narizna** [comment]
Do you think this is "good enough" to have people choose either side?

Also before approving - would we be able to also adjust republican and democratic side and have both submitted at the same time?

**Comment by sebsauve34** [comment]
Well it's a 10% consumer goods swing when making the decision to pick one or another. I think even with this change, workers is most likely stronger, but the business path would make building dockyards easier and make you a stronger navy due to having more docks while workers don't give dockyard output to offset the construction speed.  Unlocking the designer would be interesting, but not sure you would use it above the 10% construction speed until later.

**Review by GrenadierSchubes — APPROVED** [review]
Seems adequate for the situation.

**Comment by lolmemes369** [comment]
One industry path will just be better than the other especially if the balance is only around civs/mils. Same for ger, sov, and japan tbh.

**Review by lolmemes369 — APPROVED** [review]
fine change but more thought will be needed to actually make it a choice. Eventually people will just figure out the better choice.

**Comment by GrenadierSchubes** [comment]
> One industry path will just be better than the other especially if the balance is only around civs/mils. Same for ger, sov, and japan tbh.

I tend to agree

**Pull request merged**
