### PR TITLE
Debloat

### PR DESCRIPTION
**Pull request by BrianCatster**
Limited Conscription added -5%
Extensive Conscription -5%>-10%
Service By Requirement -10%>-20%
Construction and Output

Lowered Production Cap on machine tools 3, 4, and 5 10%>7.5%

Germany:
Lowered Production efficiency gain from mefo bills 25%>15%

Soviet
Removed starting 10% military factory construction speed from Soviet Military Industrial Complex
Lowered factory output from left side Soviet Military Complex by 2.5% total

SAF
Lowered Cheap Labor Output 10%>5%
Increased Focus time of Force a Debate Through Parliament 35>70 Days
Lowered supply consumption from Darkest Hour -10%>-5%

Ireland
Lowered construction speed from Ireland British Investors 10%>5% and
Lowered Resource Base from focuses
Oil 10 > 4
Tungsten 10>8
Aluminum 12>10
Steel 12>10

NZL 
Lowered Resource base from focuses
Oil 20>10
Steel 22>18 (also moved to southern island)
Tungsten 10>8 (also moved to southern island)

Italy
Removed 5% output from Vittoria Mutilata
Added -5% production to strat and nav bombers on Air Investments
Added check to control Athens to Mare Nostrum focus
Lowered Steel from pact of steel 30>25 base

France
Added -10% Stability to Prepare for War With Germany
Lowered Resource base from resource prospecting rubber
1st 10>8
2nd 15>12
Lowered Fuel gain per oil from Global Investments 25%>10%
Lowered Industry Bonuses from Develop the Countryside and metropoles 125%>100%
Lowered Mils from National Champions 4>2

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
This seems like a massive nerf to allies but you did nothing to germany?? Huh??  I do not agree with these changes.

**Comment by lolmemes369** [comment]
if u want to debloat fix the issue that everybody gets tools 1 year before the year of the tech. I don't see the point of these changes. I don't see the point of nerfing output when we just reduced plane ic and infantry ic to have more equipment.

**Comment by BrianCatster** [comment]
> if u want to debloat fix the issue that everybody gets tools 1 year before the year of the tech. I don't see the point of these changes. I don't see the point of nerfing output when we just reduced plane ic and infantry ic to have more equipment.

We reduced those ICs so we had more equipment produced in relation to everything else the machine tool changes are blanket, and also slightly nerf nations that can rush tools faster than others like UK, USA, and Germany

**Comment by BrianCatster** [comment]
> This seems like a massive nerf to allies but you did nothing to germany?? Huh?? I do not agree with these changes. Especially when Germany has a 50 pp button for 50% efficiency growth

I really only nerfed resources and slightly nerfed output on SAF and made it take 35 days longer to get Partial mob in January 1937 and made left side soviet industrial complex 2.5% less output. The removing of the starting mil construction speed on Soviet Military Industrial complex just nerfs day 1 mils, Soviets can still get the 10% once they do the mutual exclusive part of the Soviet Military Industrial Complex tree

Also Germany needs to be powerful late game to fight 3k Factory Allies while only being at the 2.5k or less factory count. The only thing Germany would need nerfing on is early game production and lowering their efficiency gain makes their newly produced mils a little weaker. You mention the 50PP button, well now there is a reason to push it. It may seem like PP is free on Germany but many of their advisors are expensive and they get negative PP as mefo increases as well as the need for PP to do important focuses.

**Comment by Narizna** [comment]
I am against doing all these all at once.

I'd much prefer only the following - have a number of games - and then review if necessary. This is my change

Limited Conscription added -5% --> -2.5%
Extensive Conscription -5%>-10% --> -5%
Service By Requirement -10%>-20% --> -7.5%
ONLY = Output

Lowered Production Cap on machine tools 3, 4, and 5 10%>7.5%

Ultimately though I feel this industry blanket nerf is just a way to nerf the 3.5 Civ output we added. I do not think any of the Nation related nerfs need to happen.

Theses 5%/10% nerfs on everything is small for each player, but massive on a scale of the entire mod.

**Comment by GrenadierSchubes** [comment]
Also real confused here why yall buffed civ production to 3.5 when trying to avoid bloat...but then go to nerf allies more than axis to help bloat... akes no sense.  You have no numbers post 42 to back these changes up, as I do not remember you in the post 42 games recently.  More data please and show how Allies are the main factor of bloat, considering games get to late 41 early 42 I am seeing it mostly on the axis in my saves.

**Comment by Mookubooku** [comment]
I agree with Gren. We need more data before making big balance changes like this.

**Comment by BrianCatster** [comment]
> I agree with Gren. We need more data before making big balance changes like this.

I think the data is sufficient, thing have been bloated for a long time and this was one suggestion a few people said to add a while ago. And anyway we have done drastic changes with limited "data" before like removing Mexico after one or two games.

**Comment by GrenadierSchubes** [comment]
> > I agree with Gren. We need more data before making big balance changes like this.
> 
> I think the data is sufficient, thing have been bloated for a long time and this was one suggestion a few people said to add a while ago. And anyway we have done drastic changes with limited "data" before like removing Mexico after one or two games.

if you think Mexico at all in any game is balanced especially the way it currently is, or is more important than major coops then you need to try a major main solo in a decent size game.  Germany main, soviet main, usa, UK main.  etc  The majority of our major players agreed it and Mongolia are NOT needed and jus meme the majors when they would prefer extra hands.

**Comment by GrenadierSchubes** [comment]
> I am against doing all these all at once.
> 
> I'd much prefer only the following - have a number of games - and then review if necessary. This is my change
> 
> Construction and Output Debuffs added: Limited Conscription added -5% --> -2.5% Extensive Conscription -5%>-10% --> -7.5%% Service By Requirement -10%>-20% --> -12.5%
> 
> Lowered Production Cap on machine tools 3, 4, and 5 10%>7.5%
> 
> Ultimately though I feel this industry blanket nerf is just a way to nerf the 3.5 Civ output we added. I do not think any of the Nation related nerfs need to happen.
> 
> Theses 5%/10% nerfs on everything is small for each player, but massive on a scale of the entire mod.
> 
> However, the stated intended target is to "debloat" which I think is just saying we want to lower 1942 and later industry bloat - in that case I sincerely believe the industry nerfs on the nations involved here is the wrong target - and should probably just be relegated to the majors as a whole.

This I would be in favor of as it is not as severe but still a large change

**Pull request closed without merging**
