### PR TITLE
Revan

### PR DESCRIPTION
**Pull request by AnonymousRevan**
rest of the adjustments to french starting forces.

made it so malise thingy goes away upon capping

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
remove free equipment swap for other items.  This is the setup, France does not need a buff to convert all their infantry to useable units

**Comment by Narizna** [comment]
as a rough estimate, is this ultimately adding, or removing starting IC? Is this adjusting existing divisions to be standard 30 widths? or just adjusting what equipment/battalions they have at start?

recent France builds I have noticed that it seems the player has a fair enough time already building a solid army. What are possible outcomes that these changes hope to provide? just able to put mil factories on other things?

**Comment by AnonymousRevan** [comment]
> as a rough estimate, is this ultimately adding, or removing starting IC? Is this adjusting existing divisions to be standard 30 widths? or just adjusting what equipment/battalions they have at start?
> 
> recent France builds I have noticed that it seems the player has a fair enough time already building a solid army. What are possible outcomes that these changes hope to provide? just able to put mil factories on other things?

France starts with units ranging from 12w to 30w. It is roughly giving them more ic cuz if the heavy tanks. I talked with rh, the idea is to take away some of their infantry based guns and such to give them more aa/at/etc. this means Germany gets less infantry equipment, forcing more mils on it like we want. I gave them more tank power, instead of 10 light tanks and 2 heavy tank divs, they get 4 heavy’s and 8 lights. They also get aa starting in their tank divs. 

All in all, they go from 30 30w inf, 35 shitty 20w, 10 lights and 2 heavy’s for 45 30w inf, 8 lights and 4 heavy’s with some stockpile left over.

**Comment by lolmemes369** [comment]
> > as a rough estimate, is this ultimately adding, or removing starting IC? Is this adjusting existing divisions to be standard 30 widths? or just adjusting what equipment/battalions they have at start?
> > recent France builds I have noticed that it seems the player has a fair enough time already building a solid army. What are possible outcomes that these changes hope to provide? just able to put mil factories on other things?
> 
> France starts with units ranging from 12w to 30w. It is roughly giving them more ic cuz if the heavy tanks. I talked with rh, the idea is to take away some of their infantry based guns and such to give them more aa/at/etc. this means Germany gets less infantry equipment, forcing more mils on it like we want. I gave them more tank power, instead of 10 light tanks and 2 heavy tank divs, they get 4 heavy’s and 8 lights. They also get aa starting in their tank divs.
> 
> All in all, they go from 30 30w inf, 35 shitty 20w, 10 lights and 2 heavy’s for 45 30w inf, 8 lights and 4 heavy’s with some stockpile left over.

So axis nerf when they alrdy need 300+ factories on planes. The problem is green air being too strong.

**Comment by GrenadierSchubes** [comment]
Comments are France is too strong still by RH at beginning phase, are we sure these are the changes we want to make?

**Review by Mookubooku — CHANGES_REQUESTED** [review]
If there's a bug in here (Malaise?), we should fix it. Otherwise, let's not buff France.

**Review by Mookubooku — APPROVED** [review]
Equipment changes are close to IC-neutral (-225 IC) so this looks good to go.

**Review by GrenadierSchubes — APPROVED** [review]
mooku approved after consultation these are within reason

**Pull request merged**
