### PR TITLE
Brian industry touches

### PR DESCRIPTION
**Pull request by BrianCatster**
Moved Retention from dispersed to concentrated
Moved base from concentrated to dispersed
Lowered mil build speed from dispersed 2.5%>1%
Lowered Max factories from state on dispersed 20%>15%
Lowered output from max stability 25%>20%
Lowered Australian, Canadian, and New Zealand starting stab by 5%
Lowered number of days required to rebuild the suez 365>180
Superior Firepower lowered supply debuff 5%>2.5%
Increased assault gun bonuses from mobile warfare 5%>10%
Modern Blitzkrieg org 3>4
Schwerpunkt added 1% coordination
Added 1% coordination to radio

### CODE REVIEW

**Review by GrenadierSchubes — APPROVED** [review]

**Review by iDealNimzi — APPROVED** [review]
I don't know the discussions surrounding this one.  So I'm approving lol

**Comment by iDealNimzi** [comment]
gotta merge it before ya close it

**Comment by Narizna** [comment]
MIL and CIV speed from disp/con could just be removed entirely in my opinion due to our increase in Civ IC build to 3.5

**Comment by lolmemes369** [comment]
add factory repair speed to dispersed 2.5% per level?

**Pull request merged**
