### PR TITLE
Small Dispersed buff

### PR DESCRIPTION
**Pull request by sebsauve34**
Re-gave dispersed 2,5% mil construction speed per tech as it was lowered for apparently no reason and nobody goes dispersed.

### CODE REVIEW

**Review by AnonymousRevan — APPROVED** [review]
thumbs up

**Comment by Narizna** [comment]
players do still go dispersed - but I do agree that it is currently the weaker choice.

I think this is just one of those issues where the CON vs DIS choice is entirely based on what nation you're playing and there will always be a "better" choice for those nations.

**Comment by Mookubooku** [comment]
I think 20% max factories is required for some minors to consider dispersed over concentrated. Also, I would keep the production efficiency base on dispersed at 5% per level. Lowering output per level on dispersed slightly is fine (i.e. 8, 10, 12, 14, 16). At concentrated V, it would have 15% production efficiency over dispersed.

However, another consideration is dockyard output. Naval nations are practically forced to go concentrated due to the higher dockyard output. I think we should equalize dockyard output between concentrated and dispersed.

I think if we make these suggested changes, it's going to be a tough choice for most players between the two.

**Comment by AnonymousRevan** [comment]
I believe italy and japan should have to choose between more bombing protection or more dock output. I do not think they should have both

**Comment by GrenadierSchubes** [comment]
Right now the only changes were sebs 1>2.5% and the lowering of efficiency from 1 every level to .75 from Teutonic.  Do we need to change anything else?

**Comment by AnonymousRevan** [comment]
> Right now the only changes were sebs 1>2.5% and the lowering of efficiency from 1 every level to .75 from Teutonic. Do we need to change anything else?

not imo

**Comment by Mookubooku** [comment]
I would like to see max factories in state reverted to +20% per level (like concentrated) and move production efficiency retention from concentrated to dispersed at all levels before signing off on this.

**Comment by GrenadierSchubes** [comment]
- get rid of the civ/mil speed and just give them const. speed, maybe half a percent more on concentrated.
- concentrated gets more output less retention (but still some), vice versa to dispersed

Lets make sure both get this option of 20% factory  and remove the bonuses to mil/civ  and just do construction higher on one by a little while the other has a higher % for production efficiency

**Review by Mookubooku — APPROVED** [review]
Looks balanced and less bloated. I approve.

**Pull request merged**
