### PR TITLE
radio changes

### PR DESCRIPTION
**Pull request by Narizna**
After game (and before game) it was noted initiative is too high, morale recovery seems too low (in general).

I lowered both coordination and initiative to 0.01. I brought back morale recovery slightly.

suggestions, changes, feedback?

### CODE REVIEW

**Review by Mookubooku — CHANGES_REQUESTED** [review]
If you look at PR #129, the default morale was 0.05 before we made any changes. I think keeping this value and the 0.02 coordination would be fine. 0.01 initiative is what we had before too but idk if trading 0.15 organization for 0.02 coordination is enough. Maybe we could bump up coordination a bit more (0.04?).

**Comment by Narizna** [comment]
> If you look at PR #129, the default morale was 0.05 before we made any changes. I think keeping this value and the 0.02 coordination would be fine. 0.01 initiative is what we had before too but idk if trading 0.15 organization for 0.02 coordination is enough. Maybe we could bump up coordination a bit more (0.04?).

keep in mind that radio stats are straight additive to divisions, similar to other equipment. So when the Techs we have that require more radios per battalion - it is adding more stats of the above. Radios at start of game are used in HQ support companies, 25 of them and it's giving 6% init at start.

After researching the support radio tech you get 1 init per support
After researching the infantry radio tech you now get 1 init per inf battalion.
after researching arty radios tech you get 1 init per battalion.
Signal is giving 25% plus the radio bonus now.

30 width infantry battalion with 7 support companies is now 25% init base. with signal (as part of the 7th) it is 51.2%. On this note anything above 0.01 for init Is a little cray. Previously only way to get init was signal company.

The main point of the change was to remove org from radios as frankly the mod gives org too freely to everyone and everything.

Further review of coordination specifically is that it is straight up not applying. it is not a stat we can use on equipment. Unless someone has evidence that it is applying otherwise, it is better to remove. From my understanding we can only "affect" stats that show on the division designer with equipment.

Radio change could be a heavily reduced Org, a good morale recovery rate, and keep the 0.01 init stat.

**Comment by lolmemes369** [comment]
> > If you look at PR #129, the default morale was 0.05 before we made any changes. I think keeping this value and the 0.02 coordination would be fine. 0.01 initiative is what we had before too but idk if trading 0.15 organization for 0.02 coordination is enough. Maybe we could bump up coordination a bit more (0.04?).
> 
> keep in mind that radio stats are straight additive to divisions, similar to other equipment. So when the Techs we have that require more radios per battalion - it is adding more stats of the above. Radios at start of game are used in HQ support companies, 25 of them and it's giving 6% init at start.
> 
> After researching the support radio tech you get 1 init per support After researching the infantry radio tech you now get 1 init per inf battalion. after researching arty radios tech you get 1 init per battalion. Signal is giving 25% plus the radio bonus now.
> 
> 30 width infantry battalion with 7 support companies is now 25% init base. with signal (as part of the 7th) it is 51.2%. On this note anything above 0.01 for init Is a little cray. Previously only way to get init was signal company.
> 
> The main point of the change was to remove org from radios as frankly the mod gives org too freely to everyone and everything.
> 
> Further review of coordination specifically is that it is straight up not applying. it is not a stat we can use on equipment. Unless someone has evidence that it is applying otherwise, it is better to remove. From my understanding we can only "affect" stats that show on the division designer with equipment.
> 
> Radio change could be a heavily reduced Org, a good morale recovery rate, and keep the 0.01 init stat.

pretty sure coordination is a country wide stat and not divisional. I say radios should include recovery rate. 

Not saying to add this but I think a lot of techs that give passives bonuses should be turned in actual equipment (prob a bad idea for industry micro sake).

Regular infantry should have all the AT and machine gun techs and be somewhat inexpensive
Light infantry should be cheap but lack AT, machine gun techs, and be slightly faster

**Comment by Mookubooku** [comment]
0.05 recovery rate is where we were at before removing the org bonuses. If we're nerfing (or removing) org by this much, I think we should bump up recovery rate to compensate (maybe test with 0.10?).

**Comment by Narizna** [comment]
final changes

**Review by RH-131 — APPROVED** [review]

**Review by lolmemes369 — APPROVED** [review]
doubling the recovery rate may be too much but I am ok with experimenting with higher recovery rates.

**Pull request merged**
