### PR TITLE
Doctrine changes

### PR DESCRIPTION
**Pull request by lolmemes369**
Take a look at the changes. GBP nerfed, Mass assault very small buff. MW slight buff. SF buff. 
Let know

Ik people said buff SF a lot but the base stats are so high late game that buffing it would allow for too high stats.

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
I don't think they are screaming for it to be hugely buffed, I also do not think they want or think GBP should be heavily nerfed.  Will wait and see what others say

**Comment by Ruling-0** [comment]
Data from this weekend's game may help nail down the specifics

**Comment by lolmemes369** [comment]
> Data from this weekend's game may help nail down the specifics
so wait for the weekend game before changing?

**Comment by sebsauve34** [comment]
wait for next game, gbp nerfs seems a bit harsh too

**Comment by Mookubooku** [comment]
I don't agree with nerfing land night attack for GBP. The other changes look fine.

**Comment by lolmemes369** [comment]
i brought back the army soft attack and hp but nerfed it slightly but kept everything else. Entrenchment speed and planning just makes GBP a less mobile doctrine. The assault path is more of the mobile path. The land night attack is still strong. 

Besides for SF I only buffed the left side since the right side is stronger (added small org buff). The tank path for SF has 5% division speed to match DB and to keep up with MW. I got rid of the MW supply consumption and added 5% div speed for the whole doctrine and another 5% speed for  MB.  The defense path gets some entrenchment. 

If you go the tank side, I added the combat width for tanks so that there are less tanks but a little bit more of stats concentrated. 

With bringing back the original grand assault with slight nerf. it should be alright now.

**Comment by GrenadierSchubes** [comment]
ah I see brian also is doing doctrines??? so uh which one are we suppose to follow??

**Comment by Mookubooku** [comment]
I don't agree with changing the supply consumption factor on large front operations. Mass mobilization is all about fitting in more troops with the same supplies.

**Comment by lolmemes369** [comment]
> I don't agree with changing the supply consumption factor on large front operations. Mass mobilization is all about fitting in more troops with the same supplies.

you can alrdy do that -15% is still a lot plus all the other bonuses. I gave an extra 24 hr supply grace too but if other people agree it is an uneeded change i can always reverse as the mass mob change as the other changes are more important tbh.

**Comment by lolmemes369** [comment]
Air doctrine 

Battlefield support:
40% ground support -> 30% ground support
cas air defense 0% -> 10%
strategic bombing 15% -> 10%

Operational integrity:
tactical bombing 10% -> 20%

Land doctrine

Mobile warfare:
added 5% division speed for the whole doctrine
Blitzkrieg path
	10% extra breakthrough to assault guns (moved from modern blitzkrieg)
	-0.2 combat width for all tank including variants and assault guns
	coordination 0.01 to 0.04
	all armor org 2 -> 4
	ground support 5% to 10%
Modern Blitzkrieg path
	added 5% division speed
	removed assault gun breakthrough
	removed -5% supply consumption
	added 5% armor division attack
Volkstrum path
	added 2% conscription
	added 2.5 entrenchment
	replaced ground support with -15% enemy air superiority 
Superior Firepower:
	replaced bonuses in the first tech with 10% division attack
	all infantry org 5-> 8
	all light infantry org 3-> 5
Integrated support path
	support battalions soft attack 30% -> 40%
  	land reinforce rate 1% -> 4%
Dispersed support path
	all line artillery recovery rate 0.20 -> 0.30 soft attack 10% -> 20%  added 2 org
	double the breakthrough for all arty brigades 50% -> 100%
air land battle path
	added 5% division speed
Mass assault:
anti tank defense 10% ->25%
Changelog for the current changes

**Review by Mookubooku — APPROVED** [review]
Looks good to me.

**Review by sebsauve34 — APPROVED** [review]
Worth trying out the changes

**Pull request merged**
