### PR TITLE
Gren's Updates and changes UK starting unit - misc

### PR DESCRIPTION
**Pull request by GrenadierSchubes**
Infantry Division upgraded to 30 width and replaced 22 light 14width divisions with these.  28 30 widths for the UK standing army

### CODE REVIEW

**Comment by Narizna** [comment]
with all of these "QoL" changes to have 20 or 30 width divisions at start - it is important to consider the possible implications, as this can help UK players do something else like tanks, but it can also have a meta player just go that much harder into planes.

I think overall maybe we should have all nations (UNLESS there is specific reason) to start with 30 width division templates - but to balance starting equipment bloat - perhaps lower the amount of divisions.

I believe that is done here? ultimately it makes it easier (again) to balance around 30 width, then multiple different division widths and who gets what and how many.

**Comment by lolmemes369** [comment]
> with all of these "QoL" changes to have 20 or 30 width divisions at start - it is important to consider the possible implications, as this can help UK players do something else like tanks, but it can also have a meta player just go that much harder into planes.
> 
> I think overall maybe we should have all nations (UNLESS there is specific reason) to start with 30 width division templates - but to balance starting equipment bloat - perhaps lower the amount of divisions.
idk. just more allied buffs lol.

**Comment by GrenadierSchubes** [comment]
people are crying about uk being nothing but a plane factory.  Then complain when they do not have infantry or enough air.  Italy I am pretty sure already starts with 30 widths as do the german spawn ins now.  Could looks at doing the same with axis minors

**Comment by lolmemes369** [comment]
> people are crying about uk being nothing but a plane factory. Then complain when they do not have infantry or enough air. Italy I am pretty sure already starts with 30 widths as do the german spawn ins now. Could looks at doing the same with axis minors

Idk why people think uk can only do planes lol. UK can have a small land army for Africa.

**Review by Mookubooku — APPROVED** [review]
Looks good to me. Shouldn't impact the early war too much; a handful more mils on planes won't really affect the air war.

**Review by Narizna — APPROVED** [review]
further review: I approve, however I believe we may need to come back to UK and adjust something elsewhere. I'll have my attention drawn to UK when reviewing post game saves to see if anything comes up.

**Pull request merged**
