### PR TITLE
Radio changes

### PR DESCRIPTION
**Pull request by GrenadierSchubes**
changed to .01 from .03 as it gave too much

### CODE REVIEW

**Review by Mookubooku — COMMENTED** [review]
Its not a signal company but maybe we can compromise on 0.02?

**Comment by lolmemes369** [comment]
> Its not a signal company but maybe we can compromise on 0.02?

No, that would be 40%

**Review by Mookubooku — CHANGES_REQUESTED** [review]
If we keep initiative at 0.01, we need to compensate the loss of organization and recovery rate with other stats.

**Review by Narizna — COMMENTED** [review]
was mentioned pre-game. game showed initiative high on many divisions.

toning it to 0.01 should make signal companies still worth to increase the stat further.

**Review by Narizna — APPROVED** [review]

**Pull request closed without merging**
