### PR TITLE
Tank manufacturers (tank design idea)

### PR DESCRIPTION
**Pull request by lolmemes369**
Please review these designer changes. Give some feedback before I add my changes to the rest of the designers. 

I would not merge until after I change all the tank designers. The rest of the designers will follow in a similar way. 

Preview: 
Uk + commonwealth - faster breakthrough tanks med/lights vs slower/more potent heavy tanks
USA - high armor/defense tanks or more firepower/some speed tanks
Axis minors will get decent tanks but not panther/tiger equivalent tanks

### CODE REVIEW

**Comment by lolmemes369** [comment]
> 
attrition, org recovery, equipment recovery

**Comment by Narizna** [comment]
I am in favor of bringing this into master - I think it'll bring interesting and clear choices to tank design.

and "if" we bring NSB tank design in - I think this will go well with that...even if I disagree with NSB tank additions.

**Comment by lolmemes369** [comment]
> I would be keen to adjust the debuffs based on feedback as some may be considered harsh or a non-factor depending on who you talk to.

yeah need feedback but generally I think the stats are ok. The designers are also for larp and flavor to a nation.

**Comment by Mookubooku** [comment]
I thought we voted against the new tank designer because it would devolve into "meta" builds anyway.

**Review by AnonymousRevan — APPROVED** [review]
Love it

**Comment by GrenadierSchubes** [comment]
Do we want this added now or is this ready?  Are all the icons present and working no '?'

**Review by Mookubooku — APPROVED** [review]
10/10 would drive more tanks into the mud.

**Review by GrenadierSchubes — APPROVED** [review]
all looks good going to merge see if it all works

**Pull request merged**
