### PR TITLE
Doctrine fixes

### PR DESCRIPTION
**Pull request by lolmemes369**
Changes to balance the doctrines some more.

Some things that could also change for SF.

keep 10% SA and 10% HA as the first but increase to 5% supply consumption.

I'm leaning towards making GBP not have 5% HA and SA but SF gets only 5% SA and HA from the first slot.

### CODE REVIEW

**Comment by sliferthegreat** [comment]
Move the armored division attack in modern blitzkrieg to earlier in the doctrine.
Replace the tank combat width with 0.4 mech combat width reduction. 
Reduce the tank HP in airland battle.
Leave GBP alone

**Comment by Narizna** [comment]
I'd rather combat width just be removed from MW in exchange for something else.

apart from that - most reports is that Org is too high in general for nearly all doctrines and stats being given from support companies. a possible balance point to consider.

**Comment by lolmemes369** [comment]
> I'd rather combat width just be removed from MW in exchange for something else.
> 
> apart from that - most reports is that Org is too high in general for nearly all doctrines and stats being given from support companies. a possible balance point to consider.

I think the combat width reduction is undervalued tbh. Besides if you really hate the combat width, you could always go the left side. Left side is more spread out. Tanks with fast infantry to encircle while the right side is more concentrated tanks and infantry used to hold the flanks.

What is the max and min org people want? 

 Radios + the headquarters tech give org btw

**Comment by sliferthegreat** [comment]
> I'd rather combat width just be removed from MW in exchange for something else.
> 
> apart from that - most reports is that Org is too high in general for nearly all doctrines and stats being given from support companies. a possible balance point to consider.

the support stats is mostly a superior firepower doctrine, and the org is really a non issue, what they really mean is HP

**Comment by lolmemes369** [comment]
> Can we get a laid out what is being changed on this? I see back and forth however would like to know we finally agreed on MW combat width changes among other doctrines? I was on vacation last 2 weeks so somewhat absent and not here to push things to be done

well I want to keep the combat width changes for now and other people disagree. People coping about combat width even though it is a buff and they don't realize it. Like people acting like they can micro 10+ tanks + other stuff super efficiently.

**Review by Mookubooku — CHANGES_REQUESTED** [review]
We should combine doctrine changes into one branch.

**Pull request closed without merging**
