### PR TITLE
Adding Industry to soviets due to Mongolia changes

### PR DESCRIPTION
**Pull request by GrenadierSchubes**
3>5 civs now in leningrad.

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
10 civs total so far and 10 mils so far. 20-30 per cac

**Review by lolmemes369 — APPROVED** [review]
should be good.

**Review by Mookubooku — APPROVED** [review]
10 civs and 13 mils is a solid buff but it seems like a good starting point. We'll have to see how it plays out.

**Comment by GrenadierSchubes** [comment]
Going to leave this up for 24 hours for further thoughts just incase

**Comment by Narizna** [comment]
probably good to not do any more than this "for now" and to see the implications of what the factories do for Russia, since getting them at the start of the game allows you to have them building things from day 1

**Comment by Ruling-0** [comment]
I'd personally go 7 civs/13 mils, +20 still but they also gained resources form the Mongolia integration so they should need less civ compensation

**Comment by Narizna** [comment]
> I'd personally go 7 civs/13 mils, +20 still but they also gained resources form the Mongolia integration so they should need less civ compensation

I would approve with this adjustment (mostly to show support)

**Comment by GrenadierSchubes** [comment]
+7 Civs +13 mils total

**Pull request merged**
