### PR TITLE
Update land_doctrine.txt

### PR DESCRIPTION
**Pull request by lolmemes369**
removed the combat width for all motorized divisions for mass mob side

Change to mass mob side still keeping it for deep battle for now

### CODE REVIEW

**Review by GrenadierSchubes — DISMISSED** [review]
Looks Good code wise

**Review by Narizna — APPROVED** [review]

**Comment by Narizna** [comment]
If mass mob needs something to replace this  I think that sounds good - otherwise I agree with change.

**Comment by Mookubooku** [comment]
veto

**Comment by Ruling-0** [comment]
I won't close this yet, but I don't believe mass mob is the issue with mass mob mech. I'd rather investigate tuning the stats so a mech division without mech equipment is just a slow infantry division.

**Pull request closed without merging**
