### PR TITLE
changes

### PR DESCRIPTION
**Pull request by GrenadierSchubes**
changes for mongolia and mexico, vichy remains but will be unplayable.

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
Map Errors reviewed and removed, Mongolia is now apart of unaligned.  No transfer of industry from Mongolia to  Russia, as most russia's never got this anyway.  Resources were transferred though to equal infrastructure state of beginning for Mongolia.  Mexico removal/anything is detrimental to the game so instead jus gave them turkish ideas so they cant produce/build anything and jus sit there as a resource slave.  Fixed map definitions in Leningrad as it seems a map change done on another branch override the lake.  Deleted any errors caused from these changes

**Review by lolmemes369 — CHANGES_REQUESTED** [review]
railway cost at 2k seems high. is it supposed to be 200 but an extra 0 was added by mistake?

**Comment by GrenadierSchubes** [comment]
Rail changes per ruling and it is the only thing we can think of that might be causing new error 55 since april 16th change

**Comment by GrenadierSchubes** [comment]
TY for checking the rail cost, must of fat fingered the zero  170 base cost to 200

**Review by lolmemes369 — APPROVED** [review]

**Review by Mookubooku — APPROVED** [review]
Looks good to me.

**Comment by GrenadierSchubes** [comment]
If Ruling sees this and wants it reviewed we can unmerge since its all one document .

**Pull request merged**
