### PR TITLE
USA Licensing Nerf

### PR DESCRIPTION
**Pull request by Ruling-0**
- All Allied nations get -18.75% licensing speed with the USA after the Nye Committee event fires
- USSR gets -16.75% licensing speed with the USA after the Nye Committee event fires

### CODE REVIEW

**Review by GrenadierSchubes — APPROVED** [review]
no funny time

**Comment by Ruling-0** [comment]
Numbers changed so the math properly cancels out the Nye committee

**Review by Mookubooku — APPROVED** [review]
Looks good.

**Comment by Narizna** [comment]
fighting abuse, one Ruling at a time.

**Pull request merged**
