### PR TITLE
Canada carrier

### PR DESCRIPTION
**Pull request by NoraValkyrie**
Added 2 Cruiser Carriers at 75% in production when you do the Carrier Focus on Canada plus it auto researches some techs for it and gives you 80 carrier planes (36 CV Fighters and Navs)

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
Means the next larp needs to be an axis ship spawn yes?

**Review by lolmemes369 — CHANGES_REQUESTED** [review]
no free tech, make it 50% with half the planes. I see no reason to give canada a freebie when the allies industry and tech to build whatever. I really don't think the allies need any more free stuff with their industry tbh

**Comment by sebsauve34** [comment]
canadian atlantic war larp sounds good to me.

**Comment by GrenadierSchubes** [comment]
as I said if we are adding in larp things for allied nations, need to compensate axis as well.

**Comment by NoraValkyrie** [comment]
For Gren. I will work on some Axis LARP next. You provided me with the Italian carriers for some larp. And I will do those next

For lolmemes. Im willing to remove the fighter plane research and spawning in. Also I am willing to lower them to 50% complete. Those would be reasonable to me.

**Comment by NoraValkyrie** [comment]
Also I'd be willing to lower it to level 1 radar.

**Comment by iDealNimzi** [comment]
@lolmemes369 I think they have to get the free tech for it to work, that's what Nora said to me in conversation.

**Review by iDealNimzi — APPROVED** [review]

**Comment by NoraValkyrie** [comment]
Yes. I believe that was causing the crashes in the first iteration was not having the tech.

**Comment by NoraValkyrie** [comment]
Will work on those tonight

**Comment by NoraValkyrie** [comment]
Heres the updates:
Made planes come from USA and not giving the tech to Canada (Since the carrier was a US built one) Also made it 30/30 (you have to build 20 planes now to make it full air wings)

Renamed it to be more historically accurate

Lowered the radar tech to radar 1 and made it so you have to have it researched to do the focus.

Lowered the Puncher completion to 50% (Kept Nabob at 70%)

**Review by GrenadierSchubes — APPROVED** [review]
Looks good in line with changes ruling requested

**Pull request merged**
