### PR TITLE
Radio, Support, Horse equipment cost

### PR DESCRIPTION
**Pull request by Narizna**
equipment cost reduction. Suggested by a couple folks that it's too high.

targeting radio and support equipment in a roughly 10% IC cost reduction.

2 steel on horses is honestly a little steep in relation to equipment resource costs for other. We could come back to resource costs for other stuff, but for horses I think this is a fair change - reduce to 1 steel per factory.

### CODE REVIEW

**Review by Mookubooku — APPROVED** [review]
I'd even be good decreasing the IC cost a bit more, down to 4 for support and 3 for radios (depending on the stats we give radios).

**Comment by Narizna** [comment]
I originally considered a rough 20% reduction of 4.2 and 3 respectively = thought it would be a bit much.

**Comment by lolmemes369** [comment]
A lot of techs need to be looked at:

Tanks/planes/arty/infantry

Resources scaling and IC scaling.

A big reason why balance builds are not possible is because of the resource issue.  Some techs are more resource efficient for putting a large amount of factories on them.

All air builds or all tanks build should come at a cost. You can do them but long term your economy will be weaker.



IC differences between tech and what they give for stats are not very balanced.

**Comment by Mookubooku** [comment]
In all fairness, I don't think 10% reduction to radios and support equipment will make a meaningful dent in the cost of a division. I think 20% (like we did with guns a few months ago) will be enough to noticeably reduce division costs but not too much to unbalance that equipment. I mainly picked 4 for support equipment and 3 for radios because I like round numbers.

Also, reducing resource cost for horses (horseshoes, carts, etc.) is a good step.

**Comment by Narizna** [comment]
> In all fairness, I don't think 10% reduction to radios and support equipment will make a meaningful dent in the cost of a division. I think 20% (like we did with guns a few months ago) will be enough to noticeably reduce division costs but not too much to unbalance that equipment. I mainly picked 4 for support equipment and 3 for radios because I like round numbers.
> 
> Also, reducing resource cost for horses (horseshoes, carts, etc.) is a good step.

I am personally inclined to pop it to 20% reduction. I am also inclined to see a game or two with it to review any noticeable differences in how players move their factories around. I leave it up to rest of the modders.

**Comment by Narizna** [comment]
20% cost reduction in place for the equipment now

**Review by RH-131 — APPROVED** [review]

**Review by lolmemes369 — APPROVED** [review]

**Pull request merged**
