### PR TITLE
Doctrine Changes

### PR DESCRIPTION
**Pull request by GrenadierSchubes**
All doctrine changes start here

Mobile - Lost all combat width, gains 10% hard and soft, Gain .15>.25 for org loss when moving.

Deep Battle - moved .25>.15 for continuous offensive

### CODE REVIEW

**Comment by GrenadierSchubes** [comment]
Please post here what else needs to be done, I also removed the org from radio and gave them coordination instead/increased initiative

**Comment by Mookubooku** [comment]
So far, I agree with Gren's changes. That said, I think we should set this as a draft until we're ready for the final review of the PR (and close conflicting PRs).

**Comment by Narizna** [comment]
> Please post here what else needs to be done, I also removed the org from radio and gave them coordination instead/increased initiative

confirming: is this removing the Org that radio gives divisions and instead having radios give coordination?

**Comment by GrenadierSchubes** [comment]
> > Please post here what else needs to be done, I also removed the org from radio and gave them coordination instead/increased initiative
> 
> confirming: is this removing the Org that radio gives divisions and instead having radios give coordination?

That is correct.  Or and default org is now removed from radios entirely and now gives this instead

**Comment by GrenadierSchubes** [comment]
I  saw cac had some changes to SF regarding org and GBP, any thoughts?

**Comment by sebsauve34** [comment]
Don't know about the 14 org for infantry doctrine, that one seems a bit overkill, at 10 it was fine. Other than that, other changes would seem good to be pushed.

**Review by Mookubooku — CHANGES_REQUESTED** [review]
I don't agree with the SF nerfs for support companies; they're unnecessary. SF and MM are in a good spot. I think we should focus more on buffing MW and, perhaps, nerfing GBP.

**Review by Mookubooku — APPROVED** [review]
Current changes look good.

**Review by sebsauve34 — APPROVED** [review]
looks good after small changes

**Review by Narizna — APPROVED** [review]
I am legit excited to see these changes on live games.

**Pull request merged**
