### PR TITLE
New naval balance

### PR DESCRIPTION
**Pull request by Ruling-0**
Shaking up the naval meta a bit. Designers cleaned up, more of a doctrinal choice than 1 best per ship class. CAs rebalanced to have some more attack, less piercing, slower, but tankier. BB/BC costs reduced significantly. Cruisers lose one turret slot. Light cruisers more visible when stacking guns.

Naval Designers
- Removed or replaced Coastal Defence Designers with Convoy Escort Designers
- Removed or replaced Battlefleet Designers with Atlantic Fleet Designers
- Pacific Fleet Designer
	- Added +5% speed to all ships
	- Added +10% AA to capitals and screens
- Atlantic Fleet Designer
	- Added -5% speed to all ships
	- Capital Ship heavy attack +10% >>> +15%
	- Capital Ship armor +10% >>> +15%
	- Added Screens +10% armor, +20% torp attack, +10% light attack
- Mediterranean Designer
	- Added +10% capital ship heavy attack
	- Added +10% screen light attack
- Raiding Designer
	- Removed -10% capital ship heavy attack
	- Added -10% capital ship hp
	- Added -10% capital ship armor
	- Added -10% screen light attack
- Convoy Escort Designer
	- Removed +10% screen IC cost
	- Added +10% screen surface detection

Ships and Modules
- Cruisers lost the ability to fit 1 battery, can fit 2 more depth charges
- Heavy ship hull IC costs reduced by 200
- Heavy ship battery IC costs reduced by 250
- Medium cruiser battery:
	- Speed penalty -4/6/7/8% >>> -6/7/8/9%
	- Surface visibility 3.5 >>> 3
	- HP 15 >>> 20
	- Armor 2 >>> 3
	- Light attack 6/6.75/7.25/8.5 >>> 6/8/10/12
	- Light piercing 17/16/23/26 >>> 8/10/12/14
- Light cruiser battery added +1 surface visibility
- Heavy ship engine IC costs reduced by 800

### CODE REVIEW

**Review by Mookubooku — APPROVED** [review]
Looks good. Should shake up the CA-spam meta.

**Review by GrenadierSchubes — APPROVED** [review]
looks good

**Comment by Ruling-0** [comment]
Adding the change I floated changing the refit bonus nations get:
- Removed -20% refit IC cost
- Added +10% dock output
- Refit speed +40%>>>+50%
- Japan's refit spirit duration 2 >>> 1.5 years
- Britain's expand dockyards refit speed 5% to 10%, removed refit ic cost
- Other refit ic cost modifiers split between refit speed and dock output

**Review by Mookubooku — APPROVED** [review]
New changes are good. I agree refit speed is a better buff to use than refit cost.

**Review by lolmemes369 — APPROVED** [review]
Seems fine

**Review by Narizna — APPROVED** [review]
My understanding of Navy is largely just good ASWs. After that I am a battleship lover - but when I have been a Major which deals in Navy my navy has typically never come to serious blows with the opponent...or the opponent's navy is of similar "balanced" composition.

all this to say is that I've personally never fought against the LC or CA spammers so I didn't know the targeted issue. That being said I think this is a clear QoL improvement for refitting stuff (along with killing off coastal designer).

**Pull request merged**
